<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;


class News extends Model
{
    protected $fillable = ['title', 'short_name', 'content', 'short_discription', 'user_id', 'img_path', 'category_id'];

    public function users()
    {
        return $this->belongsTo('App\User');
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function comment()
    {
        return $this->hasMany('App\Comment');
    }

    public function resources()
    {
        return $this->hasMany('App\Resource');
    }


    public static function getUniqueName(UploadedFile $file)
    {
        return $newname = date('Y-m-d') . '_' . time() . '_' . $file->getClientOriginalName();
    }

    public function delete()
    {
        $this->comment()->delete();
        parent::delete(); // TODO: Change the autogenerated stub
    }

}
